defaultContentLanguage = "de"
defaultContentLanguageInSubdir = "true"
title = "The green spot"
theme = "hamburg"
Paginate = 10
enableRobotsTXT = true

# Sets the "lastmod" date using git history instead of publish date
enableGitInfo = true

[sitemap]
	changefreq = 'weekly'

# Render uMap frames
[markup.goldmark.renderer]
	unsafe = true

[languages]
	[languages.en]
		languageCode = "en"
		languageName = "English"
		weight = 2
		subtitle = "Experiences from trekking, hiking and paddling in wild nature"
		copyright = "&copy; All content licensed under <a href='https://creativecommons.org/licenses/by-nc-sa/4.0/'>CC BY-NC-SA 4.0</a> license"
		[languages.en.menu]
			[[languages.en.menu.main]]
				name = "Iceland 2018"
				identifier = "iceland-2018"
				url = "pages/iceland-2018"
				weight = 4
			[[languages.en.menu.main]]
				name = "Germany"
				identifier = "germany"
				url = "pages/germany"
				weight = 3
			[[languages.en.menu.main]]
				name = "Paddling"
				identifier = "paddling"
				url = "pages/paddling"
				weight = 2
			[[languages.en.menu.main]]
				name = "About"
				identifier = "about"
				url = "pages/about"
				weight = 1
	[languages.de]
		languageCode = "de"
		languageName = "Deutsch"
		weight = 1
		subtitle = "Erfahrungen vom Trekking, Wandern und Paddeln in wilder Natur"
		copyright = "&copy; Alle Inhalte stehen unter der <a href='https://creativecommons.org/licenses/by-nc-sa/4.0/'>CC BY-NC-SA 4.0</a> Lizenz"
		[languages.de.menu]
			[[languages.de.menu.main]]
				name = "Island 2018"
				identifier = "iceland-2018"
				url = "pages/iceland-2018"
				weight = 4
			[[languages.de.menu.main]]
				name = "Deutschland"
				identifier = "germany"
				url = "pages/germany"
				weight = 3
			[[languages.de.menu.main]]
				name = "Paddeln"
				identifier = "paddling"
				url = "pages/paddling"
				weight = 2
			[[languages.de.menu.main]]
				name = "Über"
				identifier = "about"
				url = "pages/about"
				weight = 1

[params]
	# Social accounts. Link to these accounts are displayed in the header and
	# footer.
	#twitter = "Your Twitter username"
	github = "hauke96/the-green-spot"
	#gitlab = "Your GitLab username"
	#linkedin = "Your LinkedIn username"
	#googleplus = "Your Google+ user id"
	#facebook = "Your Facebook username"
	reddit = "theo_retiker"
	#hackernews = "Your Hacker News username"
	#stackoverflow = "Your Stackoverflow user id (number)"
	#keybase = "Your keybase.io username"
	#instagram = "Your Instagram username"
	# Disqus shortname
	disqus = "the-green-spot"
	# Google Analytics API key.
	#ga_api_key = "Your Google Analytics tracking id"
	# Mixpanel API key.
	#mixpanel_api_key = "Your Mixpanel API key"
	themecolor = "#9ccc65" # Defines the tab color in Chrome for Android.

	customCSS = ['hamburg.css']

	ShowGDPRNotice = true
