baseurl = "https://the-green-spot.de/"
#baseurl = "https://the-green-spot.de/beta/"
#baseUrl = "http://localhost:1313/foo"
#baseurl = "http://localhost:1313/"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = "true"
title = "The green spot"
theme = "hamburg"

[blackfriday]
	hrefTargetBlank = true

[languages]
	[languages.en]
		languageCode = "en"
		languageName = "English"
		weight = 2
		subtitle = "Trekking experiences of a different kind"
		copyright = "&copy; Everything under CC Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)"
		[languages.en.menu]
			[[languages.en.menu.main]]
				name = "About"
				identifier = "about"
				url = "pages/about"
	[languages.de]
		languageCode = "de"
		languageName = "Deutsch"
		weight = 1
		subtitle = "Erfahrungen vom Trekking der etwas anderen Art"
		copyright = "&copy; Alles steht unter CC Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)"
		[languages.de.menu]
			[[languages.de.menu.main]]
				name = "Über"
				identifier = "about"
				url = "pages/about"

[params]
	# Social accounts. Link to these accounts are displayed in the header and
	# footer.
	#twitter = "Your Twitter username"
	github = "hauke96"
	#gitlab = "Your GitLab username"
	#linkedin = "Your LinkedIn username"
	#googleplus = "Your Google+ user id"
	#facebook = "Your Facebook username"
	reddit = "theo_retiker"
	#hackernews = "Your Hacker News username"
	#stackoverflow = "Your Stackoverflow user id (number)"
	#keybase = "Your keybase.io username"
	#instagram = "Your Instagram username"
	# Disqus shortname
	#disqus = "Your disqus shortname"
	# Google Analytics API key.
	#ga_api_key = "Your Google Analytics tracking id"
	# Mixpanel API key.
	#mixpanel_api_key = "Your Mixpanel API key"
	themecolor = "#555555" # Defines the tab color in Chrome for Android.

	customCSS = ['hamburg.css']

	ShowGDPRNotice = true
	UseCommento = true
