baseurl = "https://the-green-spot.de/"
#baseurl = "localhost:1313/"
#baseurl = "http://192.168.178.29:8000/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "true"
title = "The green spot"
theme = "hamburg"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Everything under CC Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)"

[languages]
	[languages.en]
		languageCode = "en"
		subtitle = "Things about trekking we want to share"
	[languages.de]
		languageCode = "de"
		subtitle = "Dinge über trekking, die wir gerne teilen möchten"

[params]
	# Social accounts. Link to these accounts are displayed in the header and
	# footer.
	#twitter = "Your Twitter username"
	github = "hauke96"
	#gitlab = "Your GitLab username"
	#linkedin = "Your LinkedIn username"
	#googleplus = "Your Google+ user id"
	#facebook = "Your Facebook username"
	reddit = "theo_retiker"
	#hackernews = "Your Hacker News username"
	#stackoverflow = "Your Stackoverflow user id (number)"
	#keybase = "Your keybase.io username"
	#instagram = "Your Instagram username"
	# Disqus shortname
	#disqus = "Your disqus shortname"
	# Google Analytics API key.
	#ga_api_key = "Your Google Analytics tracking id"
	# Mixpanel API key.
	#mixpanel_api_key = "Your Mixpanel API key"
	#author = "Hauke & Kristina"
	#avatar = "/path/to/avatar"
	#contact = "mailto:mail@hauke-stieler.de"
	#bio = "More information soon ... :)"
	# Short subtitle/tagline. This is displayed in the header.
	themecolor = "#555555" # Defines the tab color in Chrome for Android.

	customCSS = ['vienna.css']

[menu]
  [[menu.main]]
	name = "Notes"
	weight = 10
	identifier = "notes"
	url = "site/notes/"
  [[menu.main]]
	name = "Demos"
	weight = 20
	identifier = "demos"
	url = "site/demos/"
